version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      PYTHONUNBUFFERED: 1
    command: /bin/bash -c "python src/train.py && python src/predict.py"
